### ISSUE TITLE
build: update to reflect newer versions of the gnu autotools

### ISSUE THREAD

**Issue by salewski** [salewski/ads-github-tools#79]
This issue pertains to `ads-github-tools-0.3.3`.

The author has updated the versions of the GNU Autotools used with the `ads-github-tools` project. This issue is to track changes related upgrading the tools.
```
aclocal:
   from: 1.16.1
     to: 1.16.3

automake:
   from: 1.16.1
     to: 1.16.3
```
